# AI Job Agent Configuration
# Core APIs
google_api_key: ""
google_cse_id: ""
openai_api_key: ""

# Job Discovery
search_num: 15
max_companies_per_category: 20
max_jobs_per_company: 50

# Job Classification
engine_keywords:
  - "software engineer"
  - "backend engineer"
  - "frontend engineer"
  - "full stack engineer"
  - "developer"
  - "ml engineer"
  - "data engineer"
  - "devops engineer"
  - "data scientist"
  - "product manager"

# Experience Levels
experience_levels:
  entry: ["entry", "junior", "graduate", "intern", "trainee"]
  junior: ["junior", "associate", "1-2 years"]
  mid: ["mid", "intermediate", "3-5 years", "senior associate"]
  senior: ["senior", "lead", "5+ years", "staff"]
  lead: ["lead", "principal", "architect", "manager"]
  executive: ["director", "vp", "cto", "head of"]

# Salary Ranges (USD)
salary_ranges:
  entry: [40000, 80000]
  junior: [60000, 100000]
  mid: [80000, 140000]
  senior: [120000, 200000]
  lead: [160000, 300000]
  executive: [200000, 500000]

# Company Sizes
company_sizes:
  startup: [1, 50]
  small: [51, 200]
  medium: [201, 1000]
  large: [1001, 10000]
  enterprise: [10001, 999999]

# Job Sources
job_sources:
  - name: "company_website"
    enabled: true
    priority: 1
  - name: "linkedin"
    enabled: false
    priority: 2
    api_key: ""
  - name: "indeed"
    enabled: false
    priority: 3
    api_key: ""
  - name: "glassdoor"
    enabled: false
    priority: 4
    api_key: ""

# Matching Algorithm
matching:
  weights:
    semantic_score: 0.3
    skill_match: 0.25
    experience_match: 0.2
    location_match: 0.1
    salary_match: 0.1
    company_match: 0.05
  
  thresholds:
    minimum_match_score: 0.6
    high_match_score: 0.8
    skill_match_threshold: 0.7

# Notifications
notifications:
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    from_email: ""
  
  slack:
    enabled: false
    webhook_url: ""
  
  discord:
    enabled: false
    webhook_url: ""

# Analytics
analytics:
  enabled: true
  update_frequency: "daily"  # daily, weekly, monthly
  market_trends_lookback_days: 30
  salary_benchmark_update_days: 7

# Performance
performance:
  max_concurrent_requests: 10
  request_delay_seconds: 1
  cache_ttl_hours: 24
  batch_size: 10
  
  # Caching
  cache:
    enabled: true
    redis_url: "redis://localhost:6379"
    default_ttl_seconds: 3600
  
  # Background Jobs (Celery)
  celery:
    broker_url: "redis://localhost:6379/0"
    result_backend: "redis://localhost:6379/0"
    
  # Scaling
  scaling:
    max_workers: 4
    db_pool_size: 20
    db_max_overflow: 30
  
# Web Interface
web:
  host: "0.0.0.0"
  port: 8001
  debug: false
  secret_key: "your-secret-key-here"
  
# Database
database:
  url: "sqlite:///data/db.sqlite"
  echo: false
  pool_size: 10

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/job_agent.log"
